version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      #POSTGRES_DB: smarthome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d smarthome || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - smarthome-network

  postgres_devices:
    image: postgres:16-alpine
    container_name: devices-postgres
    volumes:
      - device_postgres_data:/var/lib/postgresql/data
      - ./device-api/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      #POSTGRES_DB: device
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d device || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - smarthome-network

  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network

  telemetry-api:
    build:
      context: ./telemetry-api
      dockerfile: Dockerfile
    container_name: telemetry-api
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - smarthome-network

  device-api:
    build:
      context: ./device-api
      dockerfile: Dockerfile
    container_name: device-api
    ports:
      - "8083:8083"
    depends_on:
      postgres_devices:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres_devices:5432/device
    restart: unless-stopped
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
      device-api:
        condition: service_started
      telemetry-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
      - TELEMETRY_API_URL=http://telemetry-api:8082
      - DEVICE_API_URL=http://device-api:8083
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:
  device_postgres_data:

networks:
  smarthome-network:
    driver: bridge